name: 'latex-action'
description: 'Compile pdf from latex source'
inputs:
    working-dir:
        required: true
    latex-source:
        required: true
    diff-from:
        required: false
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.working-dir }}
        - ${{ inputs.latex-source }}
        - ${{ inputs.diff-from}}
